[package]
name = "gui"
version = "0.0.0"
edition = "2021"

[dependencies]
editor = { workspace = true }
anyhow = "1.0.71"
thiserror = "1.0"
signal-hook = "0.1.13"
crossbeam-channel = "0.4.2"
log = "0.4.8"

[dependencies.env_logger]
version = "0.7.1"
default-features = false
